### ISSUE TITLE
Need to add validations to the new transaction code

### ISSUE THREAD

**Issue by johnog65536** [johnog65536/Currency#9]
Currently I think you can double spend, and anyone can submit a spend with just the pub key.
Need soem kind of validation check & to hang the spend of one txn off the output of a previous

**Comment by domgoodwin** [comment]
I'll pick this up over the holidays and get it up on the repo

**Comment by domgoodwin** [comment]
Now when a transaction is confirmed and added it is checked against the currently tx's on the chain as well as any pending in the local queue file.

This is all pushed up to miner branch and tested locally
